### ISSUE TITLE
Can't Build WinRPM by BoundsError()

### ISSUE THREAD

**Issue by DuLiangMin** [JuliaLang/WinRPM.jl#37]
Juila 
 Version 0.3.3 (2014-11-23 20:19 UTC)
 i686-w64-mingw32

julia> versioninfo()
Julia Version 0.3.3
Commit b24213b* (2014-11-23 20:19 UTC)
Platform Info:
  System: Windows (i686-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
#####################################################

julia> Pkg.build("WinRPM")
INFO: Building WinRPM
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win3
2/openSUSE_13.1//repodata/repomd.xml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win6
4/openSUSE_13.1//repodata/repomd.xml
WARNING: encounted invalid data while parsing repomd
===============================[ ERROR: WinRPM ]================================

BoundsError()
while loading D:\Julia-0.3.3\share\julia\site\v0.3\WinRPM\deps\build.jl, in expr
ession starting on line 2

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: WinRPM had build errors.

**Comment by tkelman** [comment]
Please let us know if you have any future issues.
