### ISSUE TITLE
Starting with julia 0.3.8, remove gcc dll replacement on Windows

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/WinRPM.jl#41]
My understanding is that the dll replacement currently happening is no longer needed on more recent Julia versions, because it ships with the right dlls out of the box, correct? Would be nice to get rid of that, as that is one factor that means the default julia uninstall leaves stuff behind currently.

**Comment by tkelman** [comment]
As of Julia 0.3.7, we ship with the latest gcc dll's as of the time the binaries are built. However the repository that WinRPM pulls from is liable to change at any time. For example they've upgraded recently from gcc 4.9.2 to 5.1.0, which broke things again. I can't think of a great way off the top of my head to check whether or not the gcc dll's that happen to be present in `JULIA_HOME` match the latest versions from WinRPM.

**Comment by tkelman** [comment]
Come to think of it, we could probably be smarter about this, and use SHA.jl to compare checksums instead of leaving around a `-copy` file. I'll try to test that out locally.
