### ISSUE TITLE
I'm seeing `WinRPM.install("tk")` hang indefinitely.

### ISSUE THREAD

**Issue by twadleigh** [JuliaLang/WinRPM.jl#48]
I see:
```
julia> WinRPM.install("tk")
INFO: Packages to install: tcl, tk
Continue with install [y/N]? y
INFO: Downloading: tcl
INFO: Extracting: tcl
```
and it hangs.

I added `info(cmd)` before `WinRPM.jl:465` and got it show me:

```
INFO: Downloading: tcl
INFO: Extracting: tcl
INFO: `7z x -y 'C:\julia\v0.4\WinRPM\cache\4\noarch%2Fmingw64-tcl-8.5.15-7.17.noarch.rpm' '-oC:\julia\v0.4\WinRPM\cache\4'`
INFO: `7z x -y 'C:\julia\v0.4\WinRPM\cache\4\noarch%2Fmingw64-tcl-8.5.15-7.17.noarch.cpio' '-oC:\julia\v0.4\WinRPM\deps'`
```

Any ideas what could be going wrong here?

**Comment by twadleigh** [comment]
I can verify that it is `7z` process is hanging (or, at least, that process is not terminating), and that the corresponding command executed from the windows prompt runs successfully.

**Comment by tkelman** [comment]
That's really odd. Does it work if you manually do ```run(`7z x -y ...`)``` from the Julia REPL?

**Comment by twadleigh** [comment]
If I copy the output of my extra `INFO` message and paste it inside a `run` it executes just fine.

**Comment by twadleigh** [comment]
I tried using the `open` command:
```
julia> (out, pc) = open(`7z x 'C:\julia\v0.4\WinRPM\cache\2\noarch%2Fmingw64-tcl-8.5.15-7.17.noarch.cpio' '-oC:\julia\v0.4\WinRPM\deps'`, "r")
(Pipe(open, 0 bytes waiting),Process(`7z x 'C:\julia\v0.4\WinRPM\cache\2\noarch%2Fmingw64-tcl-8.5.15-7.17.noarch.cpio' '-oC:\julia\v0.4\WinRPM\deps'`,
 ProcessExited(2)))
```

**Comment by vtjnash** [comment]
I've seen this happen before too, also on `tcl`. I see why too:

https://github.com/JuliaLang/WinRPM.jl/blob/68c386fbcc537dda5d700adef8e482cdfd59fdc0/src/WinRPM.jl#L465-L468 is opening the STDOUT stream, but forcing the kernel to buffer it. PR submitted.
