### ISSUE TITLE
Depreciation warnings on 0.4.0

### ISSUE THREAD

**Issue by amellnik** [JuliaLang/WinRPM.jl#52]
WinRPM causes tons of depreciation warnings on 0.4.0, opening this issue to track.  I'll take a look at cleaning these up this weekend if no one beats me to it.  

Culprits include:
* WARNING: Base.String is deprecated, use AbstractString instead.
* WARNING: Union(args...) is deprecated, use Union{args...} instead.
* WARNING: Base.Uint8 is deprecated, use UInt8 instead.
* WARNING: Base.Uint16 is deprecated, use UInt16 instead.

**Comment by tkelman** [comment]
Many were probably fixed on master by #51, but haven't been tagged yet.
