### ISSUE TITLE
Segfaults on Appveyor

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/WinRPM.jl#62]
These Segfaults look like they come from WinRPM:
https://ci.appveyor.com/project/SimonDanisch/freetype-jl-bl4qr
Any ideas?

**Comment by SimonDanisch** [comment]
WinRPM.jl#53 Is this related?

**Comment by tkelman** [comment]
if you're running with julia-debug, then this is a new similar problem. There's a base issue on it. Needs someone to bisect.

**Comment by SimonDanisch** [comment]
Okay, seems to work without debug :) Guess I leave this open for now...

**Comment by tkelman** [comment]
https://github.com/JuliaLang/julia/issues/14560

**Comment by SimonDanisch** [comment]
Not really sure why it fails again after changing the README....
https://ci.appveyor.com/project/SimonDanisch/freetype-jl-bl4qr/build/job/tkcj6g0w2d2siqi7

**Comment by tkelman** [comment]
new nightlies, LibExpat.jl is broken on llvm 3.7 and probably not just on windows. it's doing something fishy with an empty union ccall return type

**Comment by nalimilan** [comment]
I've filed a separate issue (https://github.com/JuliaLang/WinRPM.jl/issues/63) for the `ReadOnlyMemoryError`, as it took me a while to understand that it's the same as the bug you described in the last comments. I suppose many people are going to report this once the get AppVeyor to fail. Better keep issues separate.

**Comment by nalimilan** [comment]
Should we close this now that the `ReadOnlyMemoryError` is gone?

**Comment by tkelman** [comment]
Does it work with julia-debug now?

**Comment by SimonDanisch** [comment]
seems fine: https://ci.appveyor.com/project/SimonDanisch/freetype-jl-bl4qr/build/1.0.7/job/eha0ta1iwfmm5045
Is `julia-debug` the preferred option for appveyor?

**Comment by tkelman** [comment]
No, not really, but it breaks more often so I"d hope someone tests it occasionally.
