### ISSUE TITLE
ReadOnlyMemoryError() with julia nightlies

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/WinRPM.jl#63]
WinRPM doesn't work with the recent Julia nightlies:
```
NFO: Building WinRPM
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download 
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download 
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
===============================[ ERROR: WinRPM ]================================ 
 
LoadError: ReadOnlyMemoryError()
while loading C:\Users\appveyor\.julia\v0.5\WinRPM\deps\build.jl, in expression starting on line 2 
 ```
https://ci.appveyor.com/project/nalimilan/stringencodings-jl/build/job/j1mjib90giq644vv

This appears to be due to libExpat not working after the recent move to LLVM 3.7.1.

**Comment by tkelman** [comment]
This is most likely a LibExpat issue so should probably be opened there.

**Comment by nalimilan** [comment]
Of course, though one would have to write a simple reproducer. Keeping this issue open doesn't hurt IMHO, it helps finding information about what's going on.

**Comment by nalimilan** [comment]
I confirm that the PR above fixed it.
