### ISSUE TITLE
Needs to use LegacyStrings

### ISSUE THREAD

**Issue by timholy** [JuliaLang/WinRPM.jl#78]
A test failure [here](https://ci.appveyor.com/project/timholy/jld-jl-28dqq/build/1.0.20/job/jd7rwx08j43l7455) suggests that the `utf16` call here needs LegacyStrings.jl. Would be nice to tag a new version when fixed.

**Comment by DrTodd13** [comment]
Yes, I'm blocked on this as well.  I managed to fix the utf16 issue locally but then it hits a utf8 issue that wasn't obvious to me how to fix since utf8 is in LegacyStrings but it was like WinRPM couldn't see it for some reason.
